spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  mongodb:
    uri: mongodb://localhost:27017/your_mongodb_database_name

server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
